### ISSUE TITLE
Error heroku

### ISSUE THREAD

**Issue by XstepAhead** [KangersHub/TorToolkitX#37] opened 2021-11-01 17:23 UTC
2021-11-01T17:15:52.285964+00:00 heroku[web.1]: State changed from starting to crashed
2021-11-01T17:15:52.046437+00:00 app[web.1]: 
2021-11-01T17:15:52.046465+00:00 app[web.1]: Error: class uri 'aiohttp.GunicornWebWorker' invalid or not found: 
2021-11-01T17:15:52.046466+00:00 app[web.1]: 
2021-11-01T17:15:52.046466+00:00 app[web.1]: [Traceback (most recent call last):
2021-11-01T17:15:52.046467+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 99, in load_class
2021-11-01T17:15:52.046467+00:00 app[web.1]:     mod = importlib.import_module('.'.join(components))
2021-11-01T17:15:52.046468+00:00 app[web.1]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-11-01T17:15:52.046468+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-11-01T17:15:52.046468+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-11-01T17:15:52.046469+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-11-01T17:15:52.046469+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2021-11-01T17:15:52.046469+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2021-11-01T17:15:52.046469+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2021-11-01T17:15:52.046470+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-11-01T17:15:52.046470+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/__init__.py", line 6, in <module>
2021-11-01T17:15:52.046470+00:00 app[web.1]:     from .client import (
2021-11-01T17:15:52.046471+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 36, in <module>
2021-11-01T17:15:52.046471+00:00 app[web.1]:     from . import hdrs, http, payload
2021-11-01T17:15:52.046471+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/http.py", line 7, in <module>
2021-11-01T17:15:52.046472+00:00 app[web.1]:     from .http_parser import (
2021-11-01T17:15:52.046472+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/http_parser.py", line 29, in <module>
2021-11-01T17:15:52.046472+00:00 app[web.1]:     from .helpers import NO_EXTENSIONS, BaseTimerContext
2021-11-01T17:15:52.046472+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 729, in <module>
2021-11-01T17:15:52.046473+00:00 app[web.1]:     def ceil_timeout(delay: Optional[float]) -> async_timeout.Timeout:
2021-11-01T17:15:52.046473+00:00 app[web.1]: AttributeError: module 'async_timeout' has no attribute 'Timeout'
2021-11-01T17:15:52.046473+00:00 app[web.1]: ]
2021-11-01T17:15:52.046473+00:00 app[web.1]: 
2021-11-01T17:15:52.087028+00:00 app[web.1]: Traceback (most recent call last):
2021-11-01T17:15:52.087030+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-11-01T17:15:52.087030+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-11-01T17:15:52.087030+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-11-01T17:15:52.087031+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2021-11-01T17:15:52.087031+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-11-01T17:15:52.087031+00:00 app[web.1]:     __import__(pkg_name)
2021-11-01T17:15:52.087032+00:00 app[web.1]:   File "/torapp/tortoolkit/__init__.py", line 16, in <module>
2021-11-01T17:15:52.087032+00:00 app[web.1]:     from tortoolkit.core.wserver import start_server
2021-11-01T17:15:52.087032+00:00 app[web.1]:   File "/torapp/tortoolkit/core/wserver.py", line 14, in <module>
2021-11-01T17:15:52.087033+00:00 app[web.1]:     from aiohttp import web
2021-11-01T17:15:52.087033+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/__init__.py", line 6, in <module>
2021-11-01T17:15:52.087034+00:00 app[web.1]:     from .client import (
2021-11-01T17:15:52.087034+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 36, in <module>
2021-11-01T17:15:52.087034+00:00 app[web.1]:     from . import hdrs, http, payload
2021-11-01T17:15:52.087034+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/http.py", line 7, in <module>
2021-11-01T17:15:52.087035+00:00 app[web.1]:     from .http_parser import (
2021-11-01T17:15:52.087035+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/http_parser.py", line 29, in <module>
2021-11-01T17:15:52.087035+00:00 app[web.1]:     from .helpers import NO_EXTENSIONS, BaseTimerContext
2021-11-01T17:15:52.087035+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 729, in <module>
2021-11-01T17:15:52.087036+00:00 app[web.1]:     def ceil_timeout(delay: Optional[float]) -> async_timeout.Timeout:
2021-11-01T17:15:52.087036+00:00 app[web.1]: AttributeError: module 'async_timeout' has no attribute 'Timeout'

**Comment by amirulandalib** [comment] 2021-11-02 07:18
@H1kikomoR1 you must have edited the code Wrongly Or Didnt Give Proper vars

**Comment by H1kikomoR1** [comment] 2021-11-02 08:03
> @H1kikomoR1 you must have edited the code Wrongly Or Didnt Give Proper vars

 i just change  docker_heroku_process_type to worker

**Comment by H1kikomoR1** [comment] 2021-11-02 08:11
> @H1kikomoR1 you must have edited the code Wrongly Or Didnt Give Proper vars

and change async-timeout==3.0.1 to async-timeout

**Comment by amirulandalib** [comment] 2021-11-02 10:48
> > @H1kikomoR1 you must have edited the code Wrongly Or Didnt Give Proper vars
> 
> and change async-timeout==3.0.1 to async-timeout

yes thats the root Cause Also If you change process to Worker from web It wont Work Properly as you expected

Change requirements to default like before if you remove dependencies it wont work And will cause Bugs and crashes...

**Comment by amirulandalib** [comment] 2021-11-03 05:00
@XstepAhead check once more i fixed it just now

**Comment by yashoswalyo** [comment] 2021-11-08 15:59
@amirulandalib issue is resolved you can close this issue

**Closed** 2021-11-17 02:45 UTC
